## Create Bill
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMyIsInVzZXJJZCI6IjY1ZDkzZDVhZjU3MDZhODc0OTNhZDQyZCIsImlhdCI6MTcwOTA3Mzk1NSwiZXhwIjoxNzA5MTAyNzU1fQ.8-7KYVFYTdcgYAric1acGaK3g0AJNBoYnqmejgz6Xe8
@billId = 65dd40692d85bac6bfd9fdf7

### Create Bill
POST http://localhost:8080/bills
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "merchant": "Mortgage",
  "amount": 1000,
  "dueDate": "2020-09-01",
  "isPaid": false,
  "isRecurring": true,
  "category": "Housing",
  "lastPaidDate": "2020-08-01"
}

### Get Bill by Id
GET http://localhost:8080/bills/{{billId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Update Bill
PATCH http://localhost:8080/bills/{{billId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

